"use client";

import React, { useEffect, useState } from "react";
import { Lightbulb, Target, TrendingUp, RefreshCw, ChevronRight, Loader2 } from "lucide-react";
import { apiClient } from "@/lib/api";

export default function RecommendationsPage() {
  const [recommendations, setRecommendations] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  const fetchData = async () => {
    try {
      const dashboard = await apiClient.get<any>('/dashboard/metrics');
      setRecommendations(dashboard.pending_actions || []);
    } catch (err) {
      console.error("Failed to load recommendations:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  const getColorClasses = (color: string) => {
    switch(color) {
      case "blue": return "bg-blue-100 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400";
      case "emerald": return "bg-emerald-100 text-emerald-600 dark:bg-emerald-900/30 dark:text-emerald-400";
      case "purple": return "bg-purple-100 text-purple-600 dark:bg-purple-900/30 dark:text-purple-400";
      default: return "bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-400";
    }
  };

  const getIcon = (type: string) => {
    switch(type) {
      case "REBALANCE": return RefreshCw;
      case "CROSS_SELL": return TrendingUp;
      case "UPSELL": return Target;
      default: return Lightbulb;
    }
  };

  const handleReview = async (recId: string) => {
    try {
      await apiClient.post(`/advisor/recommendations/${recId}/act`, {});
      setRecommendations(recommendations.filter(r => r.rec_id !== recId));
    } catch (err) {
      console.error("Failed to act on recommendation:", err);
    }
  };

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      await apiClient.post("/advisor/recommendations/generate", {});
      await fetchData();
    } catch (err) {
      console.error("Failed to generate recommendations:", err);
    } finally {
      setGenerating(false);
    }
  };

  if (loading) {
    return (
      <div className="flex-1 flex items-center justify-center bg-slate-50 dark:bg-slate-950">
        <Loader2 className="h-8 w-8 animate-spin text-blue-500" />
      </div>
    );
  }

  return (
    <div className="flex-1 overflow-auto bg-slate-50 dark:bg-slate-950 p-8 space-y-8">
      <div className="flex justify-between items-end">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-slate-900 dark:text-slate-100">
            AI Recommendations
          </h1>
          <p className="text-slate-500 dark:text-slate-400 mt-2">
            Next Best Actions generated by AI for your client book.
          </p>
        </div>
        <button 
          onClick={handleGenerate}
          disabled={generating}
          className="px-4 py-2 bg-slate-900 hover:bg-slate-800 dark:bg-slate-100 dark:hover:bg-white text-white dark:text-slate-900 rounded-lg text-sm font-medium transition-colors flex items-center space-x-2 disabled:opacity-50"
        >
          {generating ? <Loader2 className="h-4 w-4 animate-spin" /> : <Lightbulb className="h-4 w-4" />}
          <span>{generating ? 'Generating...' : 'Generate New Ideas'}</span>
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {recommendations.length === 0 ? (
          <div className="col-span-full p-8 text-center text-slate-500 bg-white dark:bg-slate-900 rounded-xl border border-dashed border-slate-200 dark:border-slate-800">
            No pending recommendations.
          </div>
        ) : recommendations.map((rec) => {
          const IconComponent = getIcon(rec.type);
          const { title, description, impact, color } = rec.payload;

          return (
            <div key={rec.rec_id} className="bg-white dark:bg-slate-900 rounded-xl shadow-sm border border-slate-200 dark:border-slate-800 p-6 flex flex-col transition-all hover:shadow-md hover:border-blue-200 dark:hover:border-blue-900">
              <div className="flex items-center justify-between mb-4">
                <span className="text-sm font-medium text-slate-500 dark:text-slate-400">{rec.client_name}</span>
                <span className={`text-xs font-semibold px-2.5 py-0.5 rounded-full ${getColorClasses(color)}`}>
                  {rec.type.replace("_", " ")}
                </span>
              </div>
              
              <div className="flex items-start space-x-4 mb-4">
                <div className={`p-2 rounded-lg ${getColorClasses(color)}`}>
                  <IconComponent className="h-5 w-5" />
                </div>
                <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100 leading-tight">
                  {title}
                </h2>
              </div>
              
              <p className="text-slate-600 dark:text-slate-300 text-sm flex-1">
                {description}
              </p>
              
              <div className="mt-6 pt-4 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between">
                <div className="flex items-center space-x-2">
                  <span className="text-xs text-slate-500 dark:text-slate-400">Impact:</span>
                  <span className={`text-xs font-semibold ${impact === 'High' ? 'text-rose-500' : 'text-amber-500'}`}>
                    {impact}
                  </span>
                </div>
                <button 
                  onClick={() => handleReview(rec.rec_id)}
                  className="text-blue-600 dark:text-blue-400 text-sm font-medium hover:underline flex items-center"
                >
                  Accept Action <ChevronRight className="h-4 w-4 ml-1" />
                </button>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
