# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ner.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tner.proto\x12\x03ner\"X\n\tNerEntity\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\r\n\x05start\x18\x03 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x04 \x01(\x05\x12\x12\n\nconfidence\x18\x05 \x01(\x02\".\n\nNerRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\"H\n\x0bNerResponse\x12 \n\x08\x65ntities\x18\x01 \x03(\x0b\x32\x0e.ner.NerEntity\x12\x17\n\x0fprocessed_in_ms\x18\x02 \x01(\x05\x32\x44\n\nNerService\x12\x36\n\x11RecognizeEntities\x12\x0f.ner.NerRequest\x1a\x10.ner.NerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NERENTITY']._serialized_start=18
  _globals['_NERENTITY']._serialized_end=106
  _globals['_NERREQUEST']._serialized_start=108
  _globals['_NERREQUEST']._serialized_end=154
  _globals['_NERRESPONSE']._serialized_start=156
  _globals['_NERRESPONSE']._serialized_end=228
  _globals['_NERSERVICE']._serialized_start=230
  _globals['_NERSERVICE']._serialized_end=298
# @@protoc_insertion_point(module_scope)
